### ISSUE TITLE
Docker volume piles up?

### ISSUE THREAD

**Issue by pcace** [ramteid/EbayKleinanzeigenCrawler#11]
Hi there,

i am running this crawler for quite some time now on a raspberry pi with great results.
The issue i have just found is that the docker volume of the docker conatiner completely fills up the system memory, since it seem to save all crawls data forever (?).

is this known or is there anything i can do to prevent it from happening? 

Thanks a lot for that great tool:)

**Comment by ramteid** [comment]
Nice to hear somebody's using it :) Yes, it's not exactly focused on saving disk space. But after ~2 years of running it didn't exceed 500 MB of disk space for me. The volume contains these things:

- logfiles: The logs are not kept forever but only these of the latest 90 days. You can tweak that in [Program.cs](https://github.com/ramteid/EbayKleinanzeigenCrawler/blob/8137b91ed35ebdbc37c66420a4d6856516856dbf/EbayKleinanzeigenCrawler/Program.cs#L68)
- `AlreadyProcessedUrls.json`: Only the found links of the last 31 days are saved (see [here](https://github.com/ramteid/EbayKleinanzeigenCrawler/blob/8137b91ed35ebdbc37c66420a4d6856516856dbf/EbayKleinanzeigenCrawler/Persistence/AlreadyProcessedUrlsPersistence.cs#L79))
- `Subscribers.json`: Contains your subscribers and their subscriptions. Is not cleaned up automatically but it shouldn't have to be as it's not prone to growing too large.
- Error log files that are NOT cleaned up automatically (`parseLink_*`, `title_*`, `validateResponse_*`): These files are html dumps that are created for debugging when errors occur. Added them for myself as they might help debugging. They are created in ParserBase.cs and QueryExecutor.cs and have to be deleted manually. If a great many errors occur, they could occupy a lot of disk space but in such cases the Crawler would be out of order anyway, I guess.

Can you provide more details about what exactly uses up that much disk space in your case?

**Comment by pcace** [comment]
Hi, for me it was around 40GB of parseLink_*, title_*, validateResponse_* files. I think i will look into deleting them on a regular basis.
thanks for the reply!

**Comment by ramteid** [comment]
You can also comment out the sections in the code where these files are created.
