### ISSUE TITLE
Can't start the telegram bot

### ISSUE THREAD

**Issue by thathome** [ramteid/EbayKleinanzeigenCrawler#6]
Hi, could someone help me. I have a telegram token but the programm ends with an errormessage.

Set token to -> 5107403883:AAEfbRANLpedjkxWJJUQVFN5XN-xxxxxxxx

ebaykleinanzeigencrawler-main-ebay-bot-1  | Unhandled exception. Autofac.Core.DependencyResolutionException: An exception was thrown while activating EbayKleinanzeigenCrawler.Scheduler.JobScheduler -> EbayKleinanzeigenCrawler.Manager.TelegramManager.
ebaykleinanzeigencrawler-main-ebay-bot-1  |  ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(EbayKleinanzeigenCrawler.Interfaces.IDataStorage, Serilog.ILogger)' on type 'TelegramManager'.
ebaykleinanzeigencrawler-main-ebay-bot-1  |  ---> System.ArgumentException: Invalid format. A valid token looks like "1234567:4TT8bAc8GHUspu3ERYn-KGcvsvGB9u_n4ddy". (Parameter 'token')
ebaykleinanzeigencrawler-main-ebay-bot-1  |    at Telegram.Bot.TelegramBotClient..ctor(String token, HttpClient httpClient)
ebaykleinanzeigencrawler-main-ebay-bot-1  |    at EbayKleinanzeigenCrawler.Manager.TelegramManager..ctor(IDataStorage dataStorage, ILogger logger) in /code/EbayKleinanzeigenCrawler/Manager/TelegramManager.cs:line 30
ebaykleinanzeigencrawler-main-ebay-bot-1  |    at lambda_method9(Closure , Object[] )

**Comment by ramteid** [comment]
@thathome It is an issue with your Telegram token. You should generate a valid token: https://core.telegram.org/bots

More detailed: Looking into the implementation of `TelegramBotClient`, there's this:
```
string[] parts = _token.Split(':');
if (parts.Length > 1 && int.TryParse(parts[0], out int id))
{
    BotId = id;
}
else
{
    throw new ArgumentException(
        "Invalid format. A valid token looks like \"1234567:4TT8bAc8GHUspu3ERYn-KGcvsvGB9u_n4ddy\".",
        nameof(token)
    );
}
```
The first part before the colon needs to be parsed to int, but `5107403883` is too large for an int. If you try to parse this part to int with `int.Parse("5107403883")`, you will get this error: `Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32.`

**Comment by thathome** [comment]
Thank you for your prompt reply. The solution to my problem was to update the telegram.bot library from v15.7.1 to v16.0.0. Now it also works with the token I get when setting up the bot.
