### ISSUE TITLE
EbayKleinanzeigenCrawler

### ISSUE THREAD

**Issue by Lc0O** [ramteid/EbayKleinanzeigenCrawler#8]
I need help. I want to try changing the code to make the bot search for elements by views, but I need to modify the program code by adding a parameter or function that allows the program to sort elements by views. However, after studying the program documentation, I couldn't find any hints there. Therefore, I would like to ask for help. I don't understand which exact code needs to be changed for my idea to start working.

**Comment by ramteid** [comment]
I'm sorry but I don't provide support. You will have to understand the code by going trough it :)
